#!/usr/bin/env ruby
# frozen_string_literal: true

script_basename = File.basename(__FILE__)
require_relative "../lib/kettle/drift/version"
if ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts Kettle::Drift::Version::VERSION
  exit(0)
end

require "kettle/drift"

puts "== #{script_basename} v#{Kettle::Drift::Version::VERSION} =="

exit(Kettle::Drift::CLI.new.run(ARGV))
