#!/usr/bin/env ruby
# frozen_string_literal: true

script_basename = File.basename(__FILE__)
repo_lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(repo_lib) if File.directory?(repo_lib) && !$LOAD_PATH.include?(repo_lib)

require "kettle/drift/version"
if ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts Kettle::Drift::Version::VERSION
  exit(0)
end

require "kettle/drift"

puts "== #{script_basename} v#{Kettle::Drift::Version::VERSION} =="

exit(Kettle::Drift::CLI.new.run(ARGV))
